spring.application.name=shipments

server.port=${PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rutaexpress}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:RutaExpress123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.open-in-view=false

catalogo.url=${CATALOGO_URL:http://localhost:8081}