spring.application.name=ms-rutaexpress-shipments
server.port=${SERVER_PORT:5000}

# Punto de verificación seguro para Docker, AWS y monitoreo básico.
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
info.app.name=ms-rutaexpress-shipments
info.app.description=Microservicio de envios de RutaExpress

# URL interna configurable para Docker y despliegue en AWS.
catalog.base-url=${CATALOGO_URL:http://localhost:8081}
