-- Ejecutar conectado como RUTAEXPRESS en el servicio FREEPDB1.
-- Este script representa el esquema controlado para ambientes compartidos y despliegues.

CREATE TABLE shipments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_seguimiento VARCHAR2(50 CHAR) NOT NULL,
    nombre_destinatario VARCHAR2(120 CHAR) NOT NULL,
    email_destinatario VARCHAR2(160 CHAR) NOT NULL,
    direccion_origen VARCHAR2(250 CHAR) NOT NULL,
    direccion_destino VARCHAR2(250 CHAR) NOT NULL,
    peso_kg NUMBER(10, 2) NOT NULL,
    estado VARCHAR2(20 CHAR) NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    fecha_actualizacion TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_shipments_codigo_seguimiento UNIQUE (codigo_seguimiento),
    CONSTRAINT ck_shipments_peso_positivo CHECK (peso_kg > 0),
    CONSTRAINT ck_shipments_estado CHECK (
        estado IN ('CREADO', 'ACEPTADO', 'EN_BODEGA', 'EN_RUTA', 'ENTREGADO', 'CANCELADO')
    )
);

CREATE INDEX ix_shipments_estado_fecha ON shipments (estado, fecha_creacion);
